"""URL mappings for the recipe app."""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from recipe import views

# Create the router instance for registering viewsets
router = DefaultRouter()
# Register the RecipeViewSet with the 'recipes' URL prefix
# This will create URLs for listing, creating, retrieving, updating and deleting recipes
router.register('recipes', views.RecipeViewSet)
router.register('tags', views.TagViewSet)
router.register('ingredients', views.IngredientViewSet)

# Define the app namespace for URL reversing
app_name = 'recipe'

# Define the URL patterns for the recipe app
urlpatterns = [
    # Include all URLs generated by the router
    # This creates endpoints like:
    # /api/recipes/ - GET (list), POST (create)
    # /api/recipes/{id}/ - GET (retrieve), PUT/PATCH (update), DELETE (delete)
    path('', include(router.urls)),
]