---
name: Checks

on:
  push:
    branches:
      - main
      - develop

jobs:
  test-lint:
    name: Test and Linting
    runs-on: ubuntu-20.04
    steps:
      # Step to login to DockerHub using credentials stored in GitHub secrets
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Step to checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step to run tests using Docker Compose
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      
      # Step to perform linting using flake8
      - name: Linting
        run: docker compose run --rm app sh -c "flake8"

     
